default_language_version:
  python: python3.9
exclude: '^.idea/|^kippi/manage\.py$|^kippi/.+/migrations/[0-9]{4}_.+\.py$'
repos:
- repo: https://github.com/ambv/black
  rev: 21.9b0
  hooks:
  - id: black
    language_version: python3.9
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=2048']
  - id: check-byte-order-marker
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude: '.+\.md'
- repo: https://gitlab.com/pycqa/flake8
  rev: '3.9.2'
  hooks:
  - id: flake8
    exclude: '__init__.py'
    args:
    - --max-line-length=88
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a4
  hooks:
  - id: pylint
    exclude: '(cli_.+|test_.+|conftest)\.py'
    args:
    - --disable=bad-continuation  # When pylint and black squabble.
    - --disable=fixme  # Allow TODO comments.
    - --disable=import-error  # pylint plugin has trouble with virtualenv imports.
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.10
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
- repo: https://github.com/KPilnacek/mirrors-bandit
  rev: 44a8790d12e9767ab946ddd9704c22cdd29479d6
  hooks:
  - id: bandit
- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.2.2
  hooks:
  - id: python-safety-dependencies-check
